### PR TITLE
Issue 84: Out of box: Removed whitelist plugin

### PR DESCRIPTION
**Pull request by dlanthier-mac**
Cause: Plugin isn't necessary. Didn't copy over for IOS.
Fix: Removing plugins from www project. Removing whitelist plugin from the required plugins.

Tested:
- iOS + Android smoke test. Blinkup + clear.
- running from both command line and IDEs.

### CODE REVIEW

**Comment by sdouglas-macadamian** [comment]
Works great on iOS (tested BlinkUp & Clear)

On Android, it works for the most part (tested BlinkUp & Clear) but the Agent URL is no longer clickable. Not sure if that's a big enough issue to warrant keeping the whitelist plugin, but it is there. Tested on master branch and it is clickable on master.

**Comment by dlanthier-mac** [comment]
Hm. So it did have a purpose.

**Comment by sdouglas-macadamian** [comment]
Appears so. On iOS it is clickable, must have different security implementations in Cordova for each platform.

**Comment by dlanthier-mac** [comment]
Yeah, then I need to figure out a way to properly add the plugin only for android.

**Pull request closed without merging**
